module.exports = Object.freeze({
  APP_NAME: "Super Admin Portal Backend",
  DEFAULT_PORT: 5000,
  DEFAULT_CORS_ORIGIN: "http://localhost:5173",
  API_RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  API_RATE_LIMIT_MAX: 200,
  REQUEST_BODY_LIMIT: "10mb",
  ACCESS_TOKEN_TTL: "7d",
  REFRESH_TOKEN_TTL: "30d",
  TOKEN_RENEWAL_THRESHOLD_SECONDS: 24 * 60 * 60,
  MONGO_SERVER_SELECTION_TIMEOUT_MS: 5000,
  MONGO_SOCKET_TIMEOUT_MS: 45000,
});
