const ROLES = {
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
  CEO: "ceo",
  HR: "hr",
  IT_MANAGER: "it_manager",
  IT_ADMIN: "it_admin",
  IT_EMPLOYEE: "it_employee",
  IT_HR: "it_hr",
  FINANCE_MANAGER: "finance_manager",
  FINANCE_EMPLOYEE: "finance_employee",
  MEDIA_HEAD: "media_head",
  MEDIA_SALES: "media_sales",
  MEDIA_MARKETING: "media_marketing",
  LAW_HEAD: "law_head",
  LAW_EMPLOYEE: "law_employee",
  FREELANCER: "freelancer",
};

const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 110,
  [ROLES.ADMIN]: 100,
  [ROLES.CEO]: 90,
  [ROLES.IT_ADMIN]: 60,
  [ROLES.LAW_HEAD]: 60,
  [ROLES.FINANCE_MANAGER]: 60,
  [ROLES.IT_MANAGER]: 60,
  [ROLES.MEDIA_HEAD]: 60,
  [ROLES.HR]: 50,
  [ROLES.IT_HR]: 50,
  [ROLES.MEDIA_SALES]: 45,
  [ROLES.MEDIA_MARKETING]: 45,
  [ROLES.IT_EMPLOYEE]: 40,
  [ROLES.FINANCE_EMPLOYEE]: 40,
  [ROLES.LAW_EMPLOYEE]: 40,
  [ROLES.FREELANCER]: 5,
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    "manage_all_users",
    "manage_all_departments",
    "view_all_data",
    "system_settings",
    "audit_logs",
    "strategic_decisions",
  ],
  [ROLES.ADMIN]: [
    "manage_all_users",
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:export",
    "roles:manage",
    "permissions:manage",
    "manage_all_departments",
    "view_all_data",
    "system_settings",
    "audit_logs",
  ],
  [ROLES.CEO]: [
    "view_all_departments",
    "approve_budgets",
    "strategic_decisions",
    "company_reports",
  ],
  [ROLES.HR]: [
    "manage_employees",
    "recruitment",
    "payroll_access",
    "performance_reviews",
    "leave_management",
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:export",
  ],
  [ROLES.IT_MANAGER]: [
    "users:read",
    "users:create",
    "users:update",
    "users:export",
    "audit_logs",
    "system_settings",
    "manage_tech_infrastructure",
    "system_access",
    "technical_support",
    "security_management",
    "manage_it_assets",
    "team_management",
    "project_oversight",
  ],
  [ROLES.IT_ADMIN]: [
    "manage_tech_infrastructure",
    "system_access",
    "technical_support",
    "security_management",
    "manage_it_assets",
  ],
  [ROLES.IT_EMPLOYEE]: [
    "system_access",
    "technical_support",
    "manage_tech_infrastructure",
    "security_management",
    "compliance_management",
    "deployment_management",
  ],
  [ROLES.IT_HR]: [
    "manage_employees",
    "recruitment",
    "performance_reviews",
    "leave_management",
    "users:read",
    "users:create",
    "users:update",
  ],
  [ROLES.LAW_HEAD]: [
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
    "approve_legal_workflows",
  ],
  [ROLES.LAW_EMPLOYEE]: [
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
  ],
  [ROLES.MEDIA_HEAD]: [
    "content_management",
    "social_media",
    "public_relations",
    "marketing_campaigns",
    "approve_media_workflows",
    "department_oversight",
    "approval_management",
    "project_oversight",
    "asset_management",
    "view_media",
    "comment_on_approvals",
  ],
  [ROLES.MEDIA_SALES]: [
    "manage_leads",
    "view_sales_reports",
    "customer_management",
    "sales_pipeline",
    "quotation_management",
    "content_management",
  ],
  [ROLES.MEDIA_MARKETING]: [
    "content_management",
    "social_media",
    "marketing_copy",
    "seo_content",
    "seo_management",
    "asset_management",
    "brand_guidelines",
    "video_production",
    "publishing",
    "advertisement_management",
    "budget_management",
    "reporting",
  ],
  [ROLES.FINANCE_MANAGER]: [
    "financial_records",
    "budget_management",
    "expense_approval",
    "financial_reports",
    "invoice_management",
    "approve_finance_workflows",
  ],
  [ROLES.FINANCE_EMPLOYEE]: [
    "financial_records",
    "budget_management",
    "expense_approval",
    "financial_reports",
    "invoice_management",
    "audit_logs",
    "view_all_data",
  ],
  [ROLES.FREELANCER]: ["view_own_profile", "view_tasks", "submit_work_reports"],
};

const isValidRole = (role) => Object.values(ROLES).includes(role);

const hasHigherOrEqualHierarchy = (userRole, targetRole) =>
  ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[targetRole];

const hasPermission = (userRole, permission) =>
  ROLE_PERMISSIONS[userRole]?.includes(permission) || false;

const getRolePermissions = (role) => ROLE_PERMISSIONS[role] || [];

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  ROLE_PERMISSIONS,
  isValidRole,
  hasHigherOrEqualHierarchy,
  hasPermission,
  getRolePermissions,
};
