const ROLES = {
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
  CEO: "ceo",
  IT: "it",
  IT_ADMIN: "it_admin",
  SYSTEM_OPERATOR: "system_operator",
  SECURITY_ANALYST: "security_analyst",
  DEVOPS_ENGINEER: "devops_engineer",
  LAW: "law",
  LEGAL_HEAD: "legal_head",
  LSW: "lsw",
  HR: "hr",
  MEDIA: "media",
  MARKETING_HEAD: "marketing_head",
  MEDIA_MANAGER: "media_manager",
  CONTENT_WRITER: "content_writer",
  GRAPHIC_DESIGNER: "graphic_designer",
  VIDEO_EDITOR: "video_editor",
  SEO_SPECIALIST: "seo_specialist",
  SOCIAL_MEDIA_MANAGER: "social_media_manager",
  PROJECT_MANAGER: "project_manager",
  DEPARTMENT_HEAD: "department_head",
  CLIENT_VIEWER: "client_viewer",
  FINANCE: "finance",
  FINANCE_MANAGER: "finance_manager",
  ACCOUNTANT: "accountant",
  AUDITOR: "auditor",
  MANAGER: "manager",
  SALES: "sales",
  RESEARCH_OPERATOR: "research_operator",
  EMPLOYEE: "employee",
  FREELANCER: "freelancer",
};

const ROLE_HIERARCHY = {
  [ROLES.SUPER_ADMIN]: 110,
  [ROLES.ADMIN]: 100,
  [ROLES.CEO]: 90,
  [ROLES.IT_ADMIN]: 60,
  [ROLES.LEGAL_HEAD]: 60,
  [ROLES.FINANCE_MANAGER]: 60,
  [ROLES.SECURITY_ANALYST]: 55,
  [ROLES.DEVOPS_ENGINEER]: 55,
  [ROLES.IT]: 50,
  [ROLES.LAW]: 50,
  [ROLES.HR]: 50,
  [ROLES.MEDIA]: 50,
  [ROLES.MARKETING_HEAD]: 55,
  [ROLES.MEDIA_MANAGER]: 45,
  [ROLES.CONTENT_WRITER]: 20,
  [ROLES.GRAPHIC_DESIGNER]: 20,
  [ROLES.VIDEO_EDITOR]: 20,
  [ROLES.SEO_SPECIALIST]: 20,
  [ROLES.SOCIAL_MEDIA_MANAGER]: 20,
  [ROLES.PROJECT_MANAGER]: 40,
  [ROLES.DEPARTMENT_HEAD]: 60,
  [ROLES.CLIENT_VIEWER]: 5,
  [ROLES.FINANCE]: 50,
  [ROLES.SALES]: 50,
  [ROLES.RESEARCH_OPERATOR]: 50,
  [ROLES.SYSTEM_OPERATOR]: 45,
  [ROLES.ACCOUNTANT]: 45,
  [ROLES.AUDITOR]: 40,
  [ROLES.MANAGER]: 40,
  [ROLES.EMPLOYEE]: 10,
  [ROLES.FREELANCER]: 5,
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    "manage_all_users",
    "manage_all_departments",
    "view_all_data",
    "system_settings",
    "audit_logs",
    "strategic_decisions",
  ],
  [ROLES.ADMIN]: [
    "manage_all_users",
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:export",
    "roles:manage",
    "permissions:manage",
    "manage_all_departments",
    "view_all_data",
    "system_settings",
    "audit_logs",
  ],
  [ROLES.CEO]: [
    "view_all_departments",
    "approve_budgets",
    "strategic_decisions",
    "company_reports",
  ],
  [ROLES.IT]: [
    "users:read",
    "users:create",
    "users:update",
    "users:export",
    "audit_logs",
    "system_settings",
    "manage_tech_infrastructure",
    "system_access",
    "technical_support",
    "security_management",
  ],
  [ROLES.IT_ADMIN]: [
    "manage_tech_infrastructure",
    "system_access",
    "technical_support",
    "security_management",
    "manage_it_assets",
  ],
  [ROLES.SYSTEM_OPERATOR]: ["system_access", "technical_support"],
  [ROLES.SECURITY_ANALYST]: ["security_management", "audit_logs", "compliance_management"],
  [ROLES.DEVOPS_ENGINEER]: ["manage_tech_infrastructure", "technical_support", "deployment_management"],
  [ROLES.LAW]: [
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
  ],
  [ROLES.LEGAL_HEAD]: [
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
    "approve_legal_workflows",
  ],
  [ROLES.LSW]: [
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
    "approve_legal_workflows",
  ],
  [ROLES.HR]: [
    "manage_employees",
    "recruitment",
    "payroll_access",
    "performance_reviews",
    "leave_management",
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:export",
  ],
  [ROLES.MEDIA]: [
    "content_management",
    "social_media",
    "public_relations",
    "marketing_campaigns",
  ],
  [ROLES.MARKETING_HEAD]: [
    "content_management",
    "social_media",
    "public_relations",
    "marketing_campaigns",
    "approve_media_workflows",
  ],
  [ROLES.MEDIA_MANAGER]: [
    "content_management",
    "social_media",
    "public_relations",
    "marketing_campaigns",
  ],
  [ROLES.CONTENT_WRITER]: [
    "content_management",
    "marketing_copy",
    "seo_content",
  ],
  [ROLES.GRAPHIC_DESIGNER]: [
    "content_management",
    "asset_management",
    "brand_guidelines",
  ],
  [ROLES.VIDEO_EDITOR]: [
    "content_management",
    "asset_management",
    "video_production",
  ],
  [ROLES.SEO_SPECIALIST]: [
    "seo_management",
    "content_management",
    "reporting",
  ],
  [ROLES.SOCIAL_MEDIA_MANAGER]: [
    "social_media",
    "publishing",
    "content_management",
  ],
  [ROLES.PROJECT_MANAGER]: [
    "project_oversight",
    "approval_management",
    "content_management",
    "asset_management",
  ],
  [ROLES.DEPARTMENT_HEAD]: [
    "department_oversight",
    "approval_management",
    "content_management",
  ],
  [ROLES.CLIENT_VIEWER]: [
    "view_media",
    "comment_on_approvals",
  ],
  [ROLES.FINANCE]: [
    "financial_records",
    "budget_management",
    "expense_approval",
    "financial_reports",
    "invoice_management",
  ],
  [ROLES.FINANCE_MANAGER]: [
    "financial_records",
    "budget_management",
    "expense_approval",
    "financial_reports",
    "invoice_management",
    "approve_finance_workflows",
  ],
  [ROLES.ACCOUNTANT]: ["financial_records", "invoice_management", "expense_approval"],
  [ROLES.AUDITOR]: ["financial_reports", "audit_logs", "view_all_data"],
  [ROLES.MANAGER]: [
    "users:read",
    "users:create",
    "users:update",
    "users:delete",
    "users:export",
    "roles:manage",
    "permissions:manage",
    "team_management",
    "project_oversight",
    "task_assignment",
    "team_reports",
    "manage_employees",
    "recruitment",
    "payroll_access",
    "performance_reviews",
    "leave_management",
    "manage_tech_infrastructure",
    "system_access",
    "technical_support",
    "security_management",
    "manage_it_assets",
    "legal_documents",
    "compliance_management",
    "contract_review",
    "legal_advice",
  ],
  [ROLES.SALES]: [
    "manage_leads",
    "view_sales_reports",
    "customer_management",
    "sales_pipeline",
    "quotation_management",
  ],
  [ROLES.RESEARCH_OPERATOR]: [
    "research_data_access",
    "research_reports",
    "data_analysis",
    "research_projects",
  ],
  [ROLES.EMPLOYEE]: [
    "view_own_profile",
    "view_tasks",
    "submit_work_reports",
    "view_attendance",
    "request_leave",
  ],
  [ROLES.FREELANCER]: ["view_own_profile", "view_tasks", "submit_work_reports"],
};

const isValidRole = (role) => Object.values(ROLES).includes(role);

const hasHigherOrEqualHierarchy = (userRole, targetRole) =>
  ROLE_HIERARCHY[userRole] >= ROLE_HIERARCHY[targetRole];

const hasPermission = (userRole, permission) =>
  ROLE_PERMISSIONS[userRole]?.includes(permission) || false;

const getRolePermissions = (role) => ROLE_PERMISSIONS[role] || [];

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  ROLE_PERMISSIONS,
  isValidRole,
  hasHigherOrEqualHierarchy,
  hasPermission,
  getRolePermissions,
};
