import React, { useCallback, useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { managerApi } from '../../services/manager';

const unwrap = (res) => res?.data ?? res ?? {};
const humanize = (v) => String(v || '').replace(/[_-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
const date = (v) => v ? new Intl.DateTimeFormat('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(v)) : 'Not set';
const Card = ({ children }) => <section className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">{children}</section>;
const Badge = ({ children }) => <span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold text-neutral-700 dark:bg-neutral-800 dark:text-neutral-200">{humanize(children)}</span>;
const Page = ({ title, description, action, children }) => <div className="min-h-screen bg-neutral-50 px-4 py-6 dark:bg-neutral-950 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">IT Management</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-neutral-500">{description}</p></div>{action}</div>{children}</div></div>;

const useManagerData = (loader, key = '') => {
  const { token } = useAuth();
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const load = useCallback(async () => { if (!token) return; setState((s) => ({ ...s, loading: true, error: '' })); try { setState({ loading: false, error: '', data: unwrap(await loader(token)) }); } catch (e) { setState({ loading: false, error: e?.message || 'Unable to load manager data.', data: null }); } }, [token, key]); // eslint-disable-line react-hooks/exhaustive-deps
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [load]);
  return { ...state, reload: load, token };
};
const State = ({ loading, error, empty, children }) => loading ? <Card><p className="animate-pulse text-sm text-neutral-500">Loading manager workspace...</p></Card> : error ? <Card><p className="text-sm text-rose-600">{error}</p></Card> : empty ? <Card><p className="text-sm text-neutral-500">No records found.</p></Card> : children;

export const ManagerDashboardPage = () => {
  const { user } = useAuth(); const { data, loading, error } = useManagerData(managerApi.getDashboard);
  const project = data?.projectSummary || {}; const task = data?.taskSummary || {}; const team = data?.teamSummary || {}; const approvals = data?.pendingApprovals || {};
  const stats = [['Active Projects', project.active || 0], ['Open Tasks', (task.total || 0) - (task.breakdown?.completed || 0)], ['Team Members', team.totalMembers || 0], ['Pending Approvals', approvals.total || 0]];
  return <Page title={`Welcome, ${user?.firstName || 'Manager'}`} description="Control IT delivery, people allocation, task execution, and approvals from one dashboard."><State loading={loading} error={error}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value]) => <Card key={label}><p className="text-sm text-neutral-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><Card><h2 className="font-bold">Upcoming tasks</h2><div className="mt-4 space-y-3">{(task.upcoming || []).map((t) => <div key={t.id} className="flex justify-between gap-3 rounded-xl bg-neutral-50 p-3 dark:bg-neutral-800"><div><p className="font-semibold">{t.title}</p><p className="text-xs text-neutral-500">{t.project?.name || 'IT'} · {date(t.dueDate)}</p></div><Badge>{t.status}</Badge></div>)}</div></Card><Card><h2 className="font-bold">Recent projects</h2><div className="mt-4 space-y-3">{(project.recent || []).map((p) => <div key={p.id} className="flex justify-between gap-3 rounded-xl bg-neutral-50 p-3 dark:bg-neutral-800"><div><p className="font-semibold">{p.name}</p><p className="text-xs text-neutral-500">{p.progress || 0}% complete</p></div><Badge>{p.status}</Badge></div>)}</div></Card></div></State></Page>;
};

export const ManagerTeamPage = () => { const { data, loading, error } = useManagerData(managerApi.getTeam); const rows = data?.team || []; return <Page title="IT Team" description="Employees allocated to your department and available for project assignment."><State loading={loading} error={error} empty={!rows.length}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map((u) => <Card key={u._id || u.id}><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-700">{u.firstName?.[0]}{u.lastName?.[0]}</div><div><p className="font-bold">{u.firstName} {u.lastName}</p><p className="text-sm text-neutral-500">{humanize(u.role)}</p></div></div><p className="mt-4 truncate text-sm text-neutral-500">{u.email}</p></Card>)}</div></State></Page>; };
export const ManagerProjectsPage = () => { const { data, loading, error } = useManagerData(managerApi.getProjects); const rows = data?.projects || []; return <Page title="Projects" description="Projects owned by you and their current delivery status."><State loading={loading} error={error} empty={!rows.length}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map((p) => <Card key={p._id || p.id}><div className="flex justify-between gap-3"><p className="font-bold">{p.name}</p><Badge>{p.status}</Badge></div><p className="mt-2 text-sm text-neutral-500">Due {date(p.deadline)}</p><div className="mt-4 h-2 rounded-full bg-neutral-100 dark:bg-neutral-800"><div className="h-2 rounded-full bg-blue-600" style={{ width: `${p.progress || 0}%` }} /></div></Card>)}</div></State></Page>; };
export const ManagerTasksPage = () => { const { data, loading, error } = useManagerData(managerApi.getTasks); const rows = data?.tasks || (Array.isArray(data) ? data : []); return <Page title="Team Tasks" description="Monitor execution across IT employees."><State loading={loading} error={error} empty={!rows.length}><div className="space-y-3">{rows.map((t) => <Card key={t._id || t.id}><div className="flex items-center justify-between gap-3"><div><p className="font-bold">{t.title}</p><p className="text-sm text-neutral-500">{t.assignedTo?.firstName || t.assignee?.name || 'Unassigned'} · Due {date(t.dueDate)}</p></div><Badge>{t.status}</Badge></div></Card>)}</div></State></Page>; };
export const ManagerWorkReviewsPage = () => { const { data, loading, error, reload, token } = useManagerData(managerApi.getEmployeeWork); const rows = data?.work || data?.items || (Array.isArray(data) ? data : []); const decide = async (id, ok) => { if (ok) await managerApi.approveWork(token, id); else await managerApi.rejectWork(token, id, 'Changes requested by manager'); reload(); }; return <Page title="Work Reviews" description="Approve submitted employee work or return it for changes."><State loading={loading} error={error} empty={!rows.length}><div className="space-y-3">{rows.map((w) => <Card key={w._id || w.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{w.title || w.task?.title || 'Work submission'}</p><p className="text-sm text-neutral-500">{w.employee?.firstName || w.employee?.name || 'Employee'}</p></div><div className="flex gap-2"><button onClick={() => decide(w._id || w.id, true)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approve</button><button onClick={() => decide(w._id || w.id, false)} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">Request changes</button></div></div></Card>)}</div></State></Page>; };
export const ManagerLeavePage = () => { const { data, loading, error, reload, token } = useManagerData(managerApi.getLeaveRequests); const rows = data?.leaves || data?.items || (Array.isArray(data) ? data : []); const decide = async (id, ok) => { if (ok) await managerApi.approveLeave(token, id); else await managerApi.rejectLeave(token, id, 'Not approved by manager'); reload(); }; return <Page title="Leave Approvals" description="Review leave requests from your IT team."><State loading={loading} error={error} empty={!rows.length}><div className="space-y-3">{rows.map((l) => <Card key={l._id || l.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{l.employee?.firstName || l.employee?.name || 'Employee'} · {humanize(l.leaveType)}</p><p className="text-sm text-neutral-500">{date(l.startDate)} — {date(l.endDate)}</p></div>{l.status === 'pending' ? <div className="flex gap-2"><button onClick={() => decide(l._id || l.id, true)} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Approve</button><button onClick={() => decide(l._id || l.id, false)} className="rounded-lg bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">Reject</button></div> : <Badge>{l.status}</Badge>}</div></Card>)}</div></State></Page>; };
