import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import Modal from '../ui/Modal';
import { departmentApi } from '../../services/departments';
import { libraryButton, libraryField } from './LibraryEditor';
import StatusBadge from '../common/StatusBadge';
import { statusToTone } from '../../utils/statusTone';

const url = value => /^https?:\/\//i.test(value || '') ? value : null;
const date = value => value ? new Date(value).toLocaleString() : '—';
const userName = value => value && typeof value === 'object' ? [value.firstName, value.lastName].filter(Boolean).join(' ') : 'Unknown user';
export default function LibraryDetail({ token, identity, id, owners, canManage, canApprove, onClose, onEdit, onNavigateItem, onRelated, onChanged }) {
  const query = useQuery({ queryKey: ['media', 'library', 'detail', identity, id], queryFn: () => departmentApi.getMediaLibraryItem(token, id), enabled: !!id, staleTime: 0 });
  const record = query.data?.data;
  const scopeQuery = useQuery({ queryKey: ['media', 'library', 'detail-owners', record?.projectId], queryFn: () => departmentApi.getMediaLibraryOverview(token, { projectId: record.projectId }), enabled: !!record });
  const projectOwners = scopeQuery.data?.data?.owners || owners;
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [shareId, setShareId] = useState(''), [scheduleDate, setScheduleDate] = useState(''), [rejectReason, setRejectReason] = useState('');
  const run = async callback => { if (busy) return; setBusy(true); setError(''); try { await callback(); await query.refetch(); onChanged(); } catch (error) { setError(error.message || 'Action failed.'); } finally { setBusy(false); } };
  const action = (action, extra = {}) => run(() => departmentApi.mediaLibraryAction(token, id, { action, expectedUpdatedAt: record.updatedAt, ...extra }));
  const field = (label, value) => <div><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm">{value || '—'}</dd></div>;
  return <Modal open title={record?.title || 'Library item'} description="Project material, relationships, approvals and recoverable versions" onClose={() => !busy && onClose()} className="sm:max-w-5xl" footer={<button className={libraryButton} disabled={busy} onClick={onClose}>Close</button>}>
    {query.isLoading ? <p role="status">Loading detail…</p> : query.isError ? <p role="alert">{query.error.message}<button onClick={() => query.refetch()} className={libraryButton}>Retry</button></p> : record ? <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-2"><StatusBadge label={record.status} tone={statusToTone(record.status)} />{record.isMaster || record.libraryKind === 'brand' ? <span className="rounded bg-teal-800 px-2 py-1 text-xs font-bold text-white">MASTER</span> : null}<span className="rounded bg-slate-100 px-2 py-1 text-xs dark:bg-neutral-800">{record.version?.current} · CURRENT VERSION</span><StatusBadge label={`Approval: ${record.approvalStatus}`} tone={statusToTone(record.approvalStatus)} /></div>
      {url(record.storageUrl) ? <div className="flex min-h-32 items-center justify-center rounded-xl bg-slate-50 p-4 dark:bg-neutral-950">
        {record.mimeType?.startsWith('image/') ? <img className="max-h-72 max-w-full rounded-lg object-contain" src={url(record.thumbnailUrl) || url(record.storageUrl)} alt={record.title} /> : record.mimeType?.startsWith('video/') ? <video className="max-h-72 max-w-full" src={url(record.storageUrl)} controls preload="metadata" /> : <a className={libraryButton} href={url(record.storageUrl)} target="_blank" rel="noreferrer">Preview file</a>}
      </div> : <p className="rounded-xl bg-slate-50 p-4 text-sm dark:bg-neutral-950">This content record has no attached file.</p>}
      <dl className="grid gap-4 sm:grid-cols-3">
        {field('Project', record.projectName)}{field('Library category', record.libraryKind)}{field('Subcategory', record.subcategory || record.category)}{field('Type', record.assetType || record.mimeType)}{field('Owner', record.ownerName)}{field('Created by', record.creatorName)}{field('Created', date(record.createdAt))}{field('Updated', date(record.updatedAt))}{field('Usage rights', record.usageRights)}{field('Expiry', date(record.expiresAt))}{field('Tags', record.tags?.map(tag => `#${tag}`).join(' '))}{field('Campaign lifecycle', record.libraryKind === 'campaigns' ? record.campaignStatus : '')}
      </dl>
      {record.description ? <p className="whitespace-pre-wrap rounded-xl border p-4 text-sm">{record.description}</p> : null}
      {record.libraryKind === 'social' ? <section className="rounded-xl border border-teal-200 p-4"><h3 className="font-bold">Social content</h3><dl className="mt-3 grid gap-4 sm:grid-cols-2">{field('Platform', record.social?.platform || record.metadata?.platform)}{field('Content type', record.social?.contentType)}{field('Caption', record.social?.caption || record.metadata?.caption)}{field('Hashtags', record.social?.hashtags?.join(' '))}{field('CTA', record.social?.cta)}{field('Target audience', record.social?.targetAudience)}{field('Scheduled', date(record.social?.scheduledAt || record.publishAt))}{field('Published', date(record.social?.publishedAt))}</dl></section> : null}
      <div className="flex flex-wrap gap-2">
        {url(record.storageUrl) && record.canDownload ? <a className={libraryButton} href={url(record.storageUrl)} target="_blank" rel="noreferrer">Download / Open Original</a> : null}
        <button className={libraryButton} disabled={busy} onClick={() => action('favorite', { enabled: !record.favorite })}>{record.favorite ? 'Remove Favorite' : 'Add Favorite'}</button>
        {canManage && !record.deletedAt ? <>
          <button className={libraryButton} disabled={busy || record.approvalStatus === 'pending'} onClick={() => onEdit(record)}>Edit / Create Version</button>
          {record.status === 'Archived' || record.archivedAt ? <button className={libraryButton} disabled={busy} onClick={() => action('unarchive')}>Restore to Library</button> : <button className={libraryButton} disabled={busy || record.approvalStatus === 'pending'} onClick={() => action('archive')}>Archive</button>}
          <button className={`${libraryButton} text-rose-700`} disabled={busy || record.approvalStatus === 'pending'} onClick={() => action('trash')}>Move to Trash</button>
          {record.approvalStatus !== 'pending' && record.approvalStatus !== 'approved' && record.status !== 'Archived' ? <button className={libraryButton} disabled={busy} onClick={() => run(() => departmentApi.submitMediaLibraryItem(token, id))}>Submit for Review</button> : null}
        </> : canManage && record.deletedAt ? <button className={libraryButton} disabled={busy} onClick={() => action('restore')}>Restore from Trash</button> : null}
      </div>
      {canManage && record.canShare && !record.deletedAt ? <div className="flex flex-wrap gap-2"><select aria-label="Share with project colleague" className={`${libraryField} mt-0 w-auto`} value={shareId} onChange={event => setShareId(event.target.value)}><option value="">Share with project colleague</option>{projectOwners.map(owner => <option key={owner.id} value={owner.id}>{owner.name}</option>)}</select><button className={libraryButton} disabled={busy || !shareId} onClick={() => action('share', { userId: shareId })}>Share</button></div> : null}
      {canManage && record.approvalStatus === 'approved' && !record.archivedAt && !record.deletedAt ? <div className="flex flex-wrap gap-2"><input aria-label="Scheduled date" type="datetime-local" className={`${libraryField} mt-0 w-auto`} value={scheduleDate} onChange={event => setScheduleDate(event.target.value)} /><button className={libraryButton} disabled={busy || !scheduleDate} onClick={() => action('schedule', { date: new Date(scheduleDate).toISOString() })}>Schedule</button><button className={libraryButton} disabled={busy} onClick={() => action('publish')}>Mark Published</button><p className="w-full text-xs text-slate-500">Tracks publishing status in this library. Publish to the platform separately.</p></div> : null}
      <section className="rounded-xl border p-4"><h3 className="font-bold">Approval history</h3><p className="mt-2 text-sm">Submitted {date(record.submittedAt)} · Approved {date(record.approvedAt)} · Rejected {date(record.rejectedAt)}</p>{record.approvalSteps?.map((step, index) => <p key={index} className="mt-2 text-sm">{step.role} · {step.status} · {userName(step.decidedBy)} · {date(step.decidedAt)} {step.remarks ? `— ${step.remarks}` : ''}</p>)}
        {canApprove && record.approvalStatus === 'pending' && record.approvalWorkflowId ? <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className={libraryButton} onClick={() => run(() => departmentApi.decideMediaApproval(token, record.approvalWorkflowId, { decision: 'approve' }))}>Approve</button><input aria-label="Rejection comments" className={`${libraryField} mt-0 w-auto`} placeholder="Reason for rejection" value={rejectReason} onChange={event => setRejectReason(event.target.value)} /><button disabled={busy || !rejectReason.trim()} className={libraryButton} onClick={() => run(() => departmentApi.decideMediaApproval(token, record.approvalWorkflowId, { decision: 'reject', remarks: rejectReason.trim() }))}>Reject with Comments</button></div> : record.approvalStatus === 'pending' && canApprove ? <Link to="/media/head/approvals" className="mt-3 inline-block text-sm text-teal-700 underline">Review is pending with Media Head</Link> : null}
      </section>
      <section className="rounded-xl border p-4"><h3 className="font-bold">Version history</h3><p className="text-xs text-slate-500">Restoring a previous version creates a new current revision and requires review.</p><div className="mt-3 space-y-3">{record.version?.history?.slice().reverse().map(version => <div key={version.number} className="flex flex-wrap items-center justify-between gap-2 border-b pb-2 text-sm"><div><strong>{version.label}{version.label === record.version.current ? ' · CURRENT' : ''}</strong><p>{userName(version.changedBy)} · {date(version.changedAt)}</p><p>{version.note}</p>{version.snapshot?.approval ? <p className="text-xs text-slate-500">Approval: {version.snapshot.approval.status} ? Approved {date(version.snapshot.approval.approvedAt)}</p> : null}</div><div className="flex gap-2">{record.canDownload && url(version.snapshot?.storageUrl) ? <a href={url(version.snapshot.storageUrl)} target="_blank" rel="noreferrer" className={libraryButton}>View File</a> : <span className="text-xs text-slate-500">No recoverable file stored</span>}{canManage && version.snapshot && !record.deletedAt ? <button disabled={busy || record.approvalStatus === 'pending' || version.label === record.version.current} className={libraryButton} onClick={() => action('restore-version', { number: version.number })}>Set as Current</button> : null}</div></div>)}</div></section>
      <section className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-bold">Related campaign & content</h3><button className={libraryButton} onClick={() => onRelated(record)}>Browse Related Material</button></div>{record.related?.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{record.related.map(item => <button key={item._id} className={`${libraryButton} text-left`} onClick={() => onNavigateItem(item._id)}>{item.title}<span className="ml-2 text-xs font-normal">{item.libraryKind || item.section}</span></button>)}</div> : <p className="mt-2 text-sm text-slate-500">No related material linked yet.</p>}</section>
      {error ? <p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}
    </div> : null}
  </Modal>;
}
