const hrModuleConfig = {
  'employee-records': {
    title: 'Employee Records',
    subtitle: 'Add and manage employee records.',
    icon: 'badge',
    endpoint: '/api/dept/hr/employees',
    dataKey: 'employees',
    kpiType: 'active',
    columns: [
      { label: 'Name', path: 'firstName' },
      { label: 'Last Name', path: 'lastName' },
      { label: 'Email', path: 'email' },
      { label: 'Role', path: 'role' },
      { label: 'Department', path: 'department' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  'employee-documents': {
    title: 'Employee Documents',
    subtitle: 'Track employee documents and approvals.',
    icon: 'folder_shared',
    endpoint: '/api/dept/hr/employee-documents',
    kpiType: 'total',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Type', path: 'documentType' },
      { label: 'Issued', path: 'issuedDate' },
      { label: 'Expiry', path: 'expiryDate' },
    ],
  },
  biometrics: {
    title: 'Employee ID/Bio Enrollment',
    subtitle: 'Manage biometric enrollments.',
    icon: 'fingerprint',
    endpoint: '/api/dept/hr/biometrics',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Enrollment ID', path: 'enrollmentId' },
      { label: 'Status', path: 'status' },
    ],
  },
  departments: {
    title: 'Department Mapping',
    subtitle: 'Manage departments and mappings.',
    icon: 'apartment',
    endpoint: '/api/dept/hr/departments',
    kpiType: 'active',
    columns: [
      { label: 'Name', path: 'name' },
      { label: 'Code', path: 'code' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  designations: {
    title: 'Designation Mapping',
    subtitle: 'Manage designations and levels.',
    icon: 'id_card',
    endpoint: '/api/dept/hr/designations',
    kpiType: 'active',
    columns: [
      { label: 'Name', path: 'name' },
      { label: 'Level', path: 'level' },
      { label: 'Department', path: 'department' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  attendance: {
    title: 'Attendance Management',
    subtitle: 'Daily attendance and corrections.',
    icon: 'calendar_month',
    endpoint: '/api/dept/hr/attendance',
    dataKey: 'attendance',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Date', path: 'date' },
      { label: 'Status', path: 'status' },
      { label: 'Check In', path: 'checkIn' },
      { label: 'Check Out', path: 'checkOut' },
    ],
  },
  'leave-requests': {
    title: 'Leave Requests',
    subtitle: 'Review and approve leave requests.',
    icon: 'hourglass_empty',
    endpoint: '/api/dept/hr/leave',
    dataKey: 'leaves',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Type', path: 'leaveType' },
      { label: 'Start', path: 'startDate' },
      { label: 'End', path: 'endDate' },
      { label: 'Status', path: 'status' },
    ],
  },
  'leave-policies': {
    title: 'Leave Policies',
    subtitle: 'Configure leave policies.',
    icon: 'policy',
    endpoint: '/api/dept/hr/leave-policies',
    kpiType: 'active',
    columns: [
      { label: 'Name', path: 'name' },
      { label: 'Type', path: 'leaveType' },
      { label: 'Days', path: 'daysPerYear' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  holidays: {
    title: 'Holiday Calendar',
    subtitle: 'Manage holidays.',
    icon: 'event',
    endpoint: '/api/dept/hr/holidays',
    kpiType: 'total',
    columns: [
      { label: 'Name', path: 'name' },
      { label: 'Date', path: 'date' },
      { label: 'Department', path: 'department' },
    ],
  },
  jobs: {
    title: 'Job Posting',
    subtitle: 'Manage job openings.',
    icon: 'work',
    endpoint: '/api/dept/hr/jobs',
    kpiType: 'status',
    columns: [
      { label: 'Title', path: 'title' },
      { label: 'Department', path: 'department' },
      { label: 'Status', path: 'status' },
    ],
  },
  applicants: {
    title: 'Applicant Tracking',
    subtitle: 'Track applicants and pipeline.',
    icon: 'group',
    endpoint: '/api/dept/hr/applicants',
    dataKey: 'applicants',
    kpiType: 'status',
    columns: [
      { label: 'Name', path: 'firstName' },
      { label: 'Last Name', path: 'lastName' },
      { label: 'Email', path: 'email' },
      { label: 'Position', path: 'position' },
      { label: 'Status', path: 'status' },
    ],
  },
  interviews: {
    title: 'Interview Scheduling',
    subtitle: 'Manage interview schedules.',
    icon: 'event_available',
    endpoint: '/api/dept/hr/interviews',
    kpiType: 'status',
    columns: [
      { label: 'Applicant', path: 'applicant.email' },
      { label: 'Stage', path: 'stage' },
      { label: 'Scheduled', path: 'scheduledAt' },
      { label: 'Status', path: 'status' },
    ],
  },
  offers: {
    title: 'Selection & Offer Making',
    subtitle: 'Create and track offers.',
    icon: 'verified',
    endpoint: '/api/dept/hr/offers',
    kpiType: 'status',
    columns: [
      { label: 'Applicant', path: 'applicant.email' },
      { label: 'Position', path: 'position' },
      { label: 'Status', path: 'status' },
    ],
  },
  performance: {
    title: 'Performance Data Collection',
    subtitle: 'Manage performance reviews.',
    icon: 'trending_up',
    endpoint: '/api/dept/hr/performance',
    dataKey: 'reviews',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Review Type', path: 'reviewType' },
      { label: 'Status', path: 'status' },
    ],
  },
  'appraisal-cycles': {
    title: 'Appraisal Cycle Tracking',
    subtitle: 'Track appraisal cycles.',
    icon: 'sync_alt',
    endpoint: '/api/dept/hr/appraisal-cycles',
    kpiType: 'status',
    columns: [
      { label: 'Name', path: 'name' },
      { label: 'Start', path: 'startDate' },
      { label: 'End', path: 'endDate' },
      { label: 'Status', path: 'status' },
    ],
  },
  appraisals: {
    title: 'Appraisal Reports',
    subtitle: 'Manage appraisal reviews.',
    icon: 'insights',
    endpoint: '/api/dept/hr/appraisals',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Cycle', path: 'cycle.name' },
      { label: 'Status', path: 'status' },
    ],
  },
  policies: {
    title: 'HR Policies & Handbook',
    subtitle: 'Publish HR policies and handbook.',
    icon: 'gavel',
    endpoint: '/api/dept/hr/policies',
    kpiType: 'active',
    columns: [
      { label: 'Title', path: 'title' },
      { label: 'Category', path: 'category' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  'policy-acknowledgements': {
    title: 'Policy Acknowledgement Tracking',
    subtitle: 'Track policy acknowledgements.',
    icon: 'task_alt',
    endpoint: '/api/dept/hr/policy-acknowledgements',
    kpiType: 'total',
    columns: [
      { label: 'Policy', path: 'policy.title' },
      { label: 'Employee', path: 'employee.email' },
      { label: 'Acknowledged', path: 'acknowledgedAt' },
    ],
  },
  notices: {
    title: 'HR Announcement',
    subtitle: 'Publish HR announcements.',
    icon: 'campaign',
    endpoint: '/api/dept/hr/notices',
    dataKey: 'notices',
    kpiType: 'active',
    columns: [
      { label: 'Title', path: 'title' },
      { label: 'Type', path: 'type' },
      { label: 'Priority', path: 'priority' },
      { label: 'Active', path: 'isActive' },
    ],
  },
  'support-tickets': {
    title: 'Employee Queries and Tickets',
    subtitle: 'Manage employee tickets.',
    icon: 'support_agent',
    endpoint: '/api/dept/hr/support-tickets',
    dataKey: 'tickets',
    kpiType: 'status',
    columns: [
      { label: 'Title', path: 'title' },
      { label: 'Priority', path: 'priority' },
      { label: 'Status', path: 'status' },
    ],
  },
  complaints: {
    title: 'Grievance Management',
    subtitle: 'Resolve grievances and complaints.',
    icon: 'report',
    endpoint: '/api/dept/hr/complaints',
    dataKey: 'complaints',
    kpiType: 'status',
    columns: [
      { label: 'Category', path: 'category' },
      { label: 'Priority', path: 'priority' },
      { label: 'Status', path: 'status' },
    ],
  },
  'exit-interviews': {
    title: 'Exit Interviews',
    subtitle: 'Manage exit interviews.',
    icon: 'logout',
    endpoint: '/api/dept/hr/exit-interviews',
    kpiType: 'status',
    columns: [
      { label: 'Employee', path: 'employee.email' },
      { label: 'Interview Date', path: 'interviewDate' },
      { label: 'Status', path: 'status' },
    ],
  },
};

export default hrModuleConfig;
