export { default as AdminLayout } from '../components/admin/AdminPortal';
export { default as CEOPortalLayout } from '../components/ceo/CEOPortal';
export { default as FinanceLayout } from '../components/finance/FinancePortal';
export { default as HRLayout } from '../components/hr/HRPortal';
export { default as ITLayout } from '../components/it/ITPortal';
export { default as LawLayout } from '../components/law/LawPortal';
export { default as OutsourcingLayout } from '../components/outsourcing/OutsourcingPortal';
export { default as EmployeeLayout } from '../components/employee/EmployeePortal';
export { default as ManagerLayout } from '../components/manager/ManagerPortal';
